CREATE TABLE IF NOT EXISTS participants (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT UNIQUE NOT NULL, access_token TEXT UNIQUE NOT NULL, blocked INTEGER NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS items (id INTEGER PRIMARY KEY AUTOINCREMENT, description TEXT NOT NULL, person TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS purchases (id INTEGER PRIMARY KEY AUTOINCREMENT, description TEXT NOT NULL, value REAL NOT NULL, person TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS invoices (id INTEGER PRIMARY KEY AUTOINCREMENT, description TEXT NOT NULL, value REAL NOT NULL, added_by TEXT NOT NULL, photo TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS shopping_notes (id INTEGER PRIMARY KEY AUTOINCREMENT, note TEXT NOT NULL, added_by TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS checklist (id INTEGER PRIMARY KEY AUTOINCREMENT, kind TEXT NOT NULL, description TEXT NOT NULL, person TEXT, done INTEGER NOT NULL DEFAULT 0, user_added INTEGER NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS rules (id INTEGER PRIMARY KEY AUTOINCREMENT, description TEXT NOT NULL, source TEXT);
CREATE TABLE IF NOT EXISTS ideas (id INTEGER PRIMARY KEY AUTOINCREMENT, kind TEXT NOT NULL, description TEXT NOT NULL, person TEXT NOT NULL);
