name = "portal-sol-api"
main = "src/index.js"
compatibility_date = "2026-10-08"

[[d1_databases]]
binding = "DB"
database_name = "portal-sol"
database_id = "8b156efb-e228-428b-8909-dc065058cfea"
migrations_dir = "migrations"
